language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-django1.8-drf2.3
    - TOX_ENV=py27-django1.8-drf2.4
    - TOX_ENV=py27-django1.8-drf3.0
    - TOX_ENV=py27-django1.8-drf3.1
    - TOX_ENV=py33-django1.8-drf3.1
    - TOX_ENV=py34-django1.8-drf2.3
    - TOX_ENV=py34-django1.8-drf2.4
    - TOX_ENV=py34-django1.8-drf3.0
    - TOX_ENV=py34-django1.8-drf3.1

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
